### ISSUE TITLE
Where is `platforms/android` before building ?

### ISSUE THREAD

**Issue by kunal15595** [shubhamshuklaer/jarvis#1]

**Comment by shubhamshuklaer** [comment]
Oh sorry I didn't notice. Its was it .gitignore by default. You need to do "ionic platform add android" . I have moved the gradle.properties.example file outside.

**Comment by kunal15595** [comment]
where outside?

**Comment by shubhamshuklaer** [comment]
In root directory.

**Comment by kunal15595** [comment]
and in which directory it should be?
